version: '3.10'
services:
  ator-backend:
    build: .
    command: python run.py
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  prefect-server:
    image: prefecthq/server:latest
    ports:
      - "8080:8080"

  prefect-agent:
    image: prefecthq/prefect:latest
    depends_on:
      - prefect-server
    environment:
      - PREFECT__CLOUD__AGENT__LABELS=['local']
      - PREFECT__CLOUD__API='http://prefect-server:4200'

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: orchestrator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
