version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
      - run:
          name: Trigger Prefect Flow
          command: |
            # Add command to trigger Prefect flow here

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
