pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest'
            }
        }
        stage('Deploy with Prefect') {
            steps {
                // Add command to trigger Prefect flow here
            }
        }
    }
}
